//! Docker-free prestate coverage of the invariant and projection layers.
//!
//! Two cases, both replayed with no node and no Docker so a regression in the harness itself
//! surfaces in the default workspace run:
//!
//! * `nop_transfer` — a hand-written fixture asserted against the property invariants and a
//!   projection golden, the same two layers `base-system-tests`' `firehose_b20` uses.
//! * `base_mainnet_replay` — a real Base mainnet transaction, generated by
//!   `base-firehose-prestate`, whose golden was seeded from production Firehose so that its first
//!   run validated the generator and the tracer against production. Both are ordinary goldens now.

use std::path::PathBuf;

use alloy_primitives::{B256, b256};
use base_firehose_tests::{
    BlockInvariants, BlockProjection, Golden, ProductionReplay, SymbolTable, VolatilePolicy,
    run_prestate,
};

#[test]
fn nop_transfer() {
    let folder = case_dir();
    let outcome = run_prestate(&folder).expect("nop_transfer prestate must succeed");

    BlockInvariants::assert(&outcome.block).expect("captured block must satisfy the invariants");

    let trace = outcome
        .block
        .transaction_traces
        .first()
        .expect("nop_transfer block must hold one transaction");

    let symbols = SymbolTable::new()
        .with(&trace.from, "sender")
        .with(&trace.to, "recipient")
        .with(&outcome.block.header.as_ref().expect("header").coinbase, "coinbase");

    // A prestate replay is fully reproducible (no live node moving the base fee or the clock), so
    // keep every field — `VolatilePolicy::none()` — and let the golden catch the most it can.
    let projection = BlockProjection::new()
        .with_symbols(symbols)
        .with_policy(VolatilePolicy::none())
        .transaction(&outcome.block, &trace.hash)
        .expect("projecting the transaction must succeed");

    Golden::is_json_equal(&projection, &folder.join("block.2099.json"))
        .expect("comparing against golden must not error")
        .assert_equal();
}

/// Replays a real Base mainnet transaction generated by `base-firehose-prestate`.
///
/// `prestate.json` came from `base-firehose-prestate generate` against an archive node. The golden
/// was *seeded* by `base-firehose-prestate reference`, which writes the transaction exactly as
/// StreamingFast's production Firehose recorded it — so the first run of this test was a direct
/// comparison against production, and it matched. That validation is a one-off: it proved the
/// generator and the tracer agree with production, and from here the golden is an ordinary one,
/// regenerated with `GOLDEN_UPDATE=1` like every other. No test needs credentials or a production
/// endpoint, and further cases only need `generate`.
///
/// [`ProductionReplay`] is what made that first comparison possible: the replay runs the
/// transaction alone in a synthetic single-transaction block, so it excludes the block-wide
/// positional fields (ordinals, the transaction's index, each log's block index, the cumulative gas
/// used) and keeps everything else — gas accounting, the call tree, logs and absolute balance,
/// nonce and storage values.
#[test]
fn base_mainnet_replay() {
    const TX: B256 = b256!("0x32ecdb4e72df6ec331edb81256b58a768ba49d1e3e89a1a071b980a85d6b72c0");

    let folder = cases_dir().join("base_mainnet_replay");
    let outcome = run_prestate(&folder).expect("base_mainnet_replay prestate must succeed");

    BlockInvariants::assert(&outcome.block).expect("captured block must satisfy the invariants");

    let projection = ProductionReplay::projection()
        .transaction(&outcome.block, TX.as_slice())
        .expect("projecting the replayed transaction must succeed");

    Golden::is_json_equal(&projection, &folder.join("block.49663794.json"))
        .expect("comparing against golden must not error")
        .assert_equal();
}

fn case_dir() -> PathBuf {
    cases_dir().join("nop_transfer")
}

fn cases_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests").join("cases")
}
